### ISSUE TITLE
please update main readme.md, docker section with explanation what is sane defaults

### ISSUE THREAD

**Issue by asida** [YottaDB/YDB#358]
dear maintainers,
first, thank you for great job here !!!

I've read many articles before went here to try yotta, but have no idea what this mean (readme.md):
...
Image information

The docker image is built using the generic ydb script that gives the user some sane defaults to begin exploring YottaDB. This isn't meant for production usage.
...

can you please be more specific about these "sane defaults" ? I would appreciate list of such defaults (disabled/enabled), where to change and if any is complex then even link to docs (as docs are very comprehensive)

thank you in advance

AS.

**Comment by shabiel** [comment]
@asida We use https://docs.yottadb.com/AdminOpsGuide/basicops.html#ydb-env-set in the docker image to set the environment defaults. The important ones are:

- ydb_rel/ydb_dir are the directories
- ydb_dist (where YottaDB lives)
- ydb_gbldir (database definition file: we create a global directory based on https://gitlab.com/YottaDB/DB/YDB/-/blob/master/sr_unix/gdedefaults.gtc)
- ydb_routines (location of M code)
- ydb_chset (default to UTF-8 mode rather than the legacy M mode)

**Comment by asida** [comment]
thank you very much Sam for response and sorry for mistake, I missed notice that this is just replica of gitlab orig repo,. I'll post to gitlab all future find outs :)
b.r.
A.

**Comment by asida** [comment]
I forgot to close, apologies
